### ISSUE TITLE
建议增加可选鼠标穿透功能

### ISSUE THREAD

**Issue by vvair** [CodeFalling/MacGesture#133]
在大屏幕上, 我们通常打开多个窗口使用.

比如我现在屏幕同时打开A B C 软件, 我正在使用A软件(A是激活窗口), 
想要关闭 B 或 C 软件, 正常操作是把鼠标移动过去, 手势关闭. 
但是现在的情况是,  我直接操作手势, 关闭的是A软件, 
现在需要先激活B或C后, 才能使用响应鼠标手势, 不太方便,

建议增加鼠标穿透功能, 以鼠标所在位置下的软件为响应目标, 而不是现在的以激活窗口为响应目标.
谢谢

**Comment by bytemain** [comment]
Same as: https://github.com/MacGesture/MacGesture/issues/115
