### ISSUE TITLE
High CPU usage (~30% on M1 Pro) whenever I move the mouse

### ISSUE THREAD

**Issue by ingjieye** [CodeFalling/MacGesture#138]
**Describe the bug**
The MacGesture uses ~30% of the CPU on M1 Pro whenever I move the mouse.

**Steps To Reproduce**
1. Enable MacGesture
2. Move the mouse without any key press

**Expected behaviour**
Should not use high CPU when not pressing any keys

**Screenshots**
<img width="353" alt="image" src="https://github.com/MacGesture/MacGesture/assets/13421169/789548d2-a3f1-491f-9e15-9d82afe808c8">

**Desktop (please complete the following information):**
 - OS: macOS 13.5 (22G74)
 - Browser Firefox, 
 - Version 3.2.0

**Additional context**
No

**Comment by bytemain** [comment]
<img width="1290" alt="image" src="https://github.com/MacGesture/MacGesture/assets/13938334/95be05c9-1750-4007-86b5-3880492f76e9">

did you use the right arch of your computer?

**Comment by ingjieye** [comment]
> <img alt="image" width="1290" src="https://user-images.githubusercontent.com/13938334/270915055-95be05c9-1750-4007-86b5-3880492f76e9.png">
> 
> did you use the right arch of your computer?

Yes, It's 'Apple'

**Comment by ingjieye** [comment]
Here's a trace file I ran using Xcode's profiler, it occurs at 45 to 60 seconds.
Seems the major CPU usage has nothing to do with MacGesture, but a problem with macOS, A higher mouse polling rate is likely to cause the problem (mine is 1000hz)

https://news.ycombinator.com/item?id=27571523

[45s~60s.trace.zip](https://github.com/MacGesture/MacGesture/files/12840912/45s.60s.trace.zip)
<img width="654" alt="图片" src="https://github.com/MacGesture/MacGesture/assets/13421169/71ad1304-baa0-451c-9aac-210bb0aad6ef">

**Comment by ingjieye** [comment]
I've changed the polling rate to 125hz, and the CPU usage is reduced to ~5%
<img width="332" alt="图片" src="https://github.com/MacGesture/MacGesture/assets/13421169/15fe9245-71a1-40c8-a7e8-c314b2af15b1">
