### ISSUE TITLE
反馈一下,感谢作者的好软件

### ISSUE THREAD

**Issue by hstdt** [CodeFalling/MacGesture#25]
刚用上一会,然后立刻就把chrome里面的手势扩展卸了,原来单击右键出来的菜单,现在得双击,手都点累了.
言归正传,说说我用了之后的感觉,仅供参考.
1.Rules->Filter 点击Pick后,是不是将这个改成增加和删除模式会更好,而不是目前的覆盖模式.(黑白名单里面的那种模式),一不小心就要哭着重新勾选了.
2.点击Go bigger之后,按钮文字也没变,我还以为一直能大大大下去呢=.=
3.默认里面还可以把U和D分别对应Home(Fn + Left arrow) 和End(Fn + Right arrow),看起来功能会更丰满.
4.还希望能有配置导入导出功能,如果换电脑,或者进行备份/修改(测试)规则,有这个也能方便很多.

**Comment by CodeFalling** [comment]
1.确实需要解决，已经在计划中了，参见 #24 
2.表示不是我加的功能-。-我也挺疑惑是干嘛使的。。
3.默认的手势目测没有需求的话不会再改，防止覆盖已有的设置
4.关于Mac应用的配置是有通用解决方案的，参见 https://manytricks.com/blog/?p=3049

**Comment by hstdt** [comment]
@CodeFalling  

2.Go bigger点击之后,窗口会变大,再点击变回来,这时候文字应该变成Go smaller更合适点.
4.明白了,配置文件都在默认的plist文件里
~/Library/Preferences/com.codefalling.MacGesture.plist

**Comment by CodeFalling** [comment]
@hstdt 
确实，有空会改过来。
恩，不过备份和替换等还是有点麻烦，参照上面那篇文章替换才行，好像是因为plist会有缓存的原因。

感谢使用和反馈 :smile:

**Comment by CodeFalling** [comment]
我给这个软件建立了一个wiki页（在我的个人wiki上），任何人都可以编辑，我已经把你提到的几点加进去了

**Comment by jiegec** [comment]
可以加到2.0.9那个milestone里面

**Comment by CodeFalling** [comment]
@jiegec 还没决定下个版本要做哪些功能呢，，最近要找实习了又没啥时间_(:з」∠)_

**Comment by jiegec** [comment]
Now merged into develop.
