### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by CodeFalling** [CodeFalling/MacGesture#30]
![2016-04-06 12 02 08](https://cloud.githubusercontent.com/assets/5436704/14305544/f3b53f26-fbef-11e5-919b-fa5a438081b2.png)

Mouse path drawing is too slow.

**Comment by jiegec** [comment]
Fixed? If yes, it's time to publish a new version.

**Comment by CodeFalling** [comment]
Probably yes! I'll release a new version.
